input_language = "Russian"
output_language = "English (US)"
language_codes = {
    "Afrikaans": "af-ZA",
    "Amharic": "am-ET",
    "Arabic": "ar-XA",
    "Armenian": "hy-AM",
    "Azerbaijani": "az-AZ",
    "Basque": "eu-ES",
    "Belarusian": "be-BY",
    "Bengali": "bn-IN",
    "Bosnian": "bs-BA",
    "Bulgarian": "bg-BG",
    "Cantonese (Traditional)": "yue-Hant-HK",
    "Catalan": "ca-ES",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Croatian": "hr-HR",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Dutch": "nl-NL",
    "English (Australia)": "en-AU",
    "English (Canada)": "en-CA",
    "English (India)": "en-IN",
    "English (New Zealand)": "en-NZ",
    "English (South Africa)": "en-ZA",
    "English (UK)": "en-GB",
    "English (US)": "en-US",
    "Estonian": "et-EE",
    "Filipino": "fil-PH",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "French (Canada)": "fr-CA",
    "Galician": "gl-ES",
    "Georgian": "ka-GE",
    "German": "de-DE",
    "Greek": "el-GR",
    "Gujarati": "gu-IN",
    "Hebrew": "he-IL",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Icelandic": "is-IS",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Javanese": "jv-ID",
    "Kannada": "kn-IN",
    "Khmer": "km-KH",
    "Korean": "ko-KR",
    "Lao": "lo-LA",
    "Latvian": "lv-LV",
    "Lithuanian": "lt-LT",
    "Macedonian": "mk-MK",
    "Malay": "ms-MY",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Mongolian": "mn-MN",
    "Nepali": "ne-NP",
    "Norwegian": "no-NO",
    "Persian": "fa-IR",
    "Polish": "pl-PL",
    "Portuguese": "pt-PT",
    "Portuguese (Brazil)": "pt-BR",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Serbian": "sr-RS",
    "Sinhalese": "si-LK",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Spanish": "es-ES",
    "Spanish (Latin America)": "es-419",
    "Sundanese": "su-ID",
    "Swahili": "sw-TZ",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Urdu": "ur-PK",
    "Uzbek": "uz-UZ",
    "Vietnamese": "vi-VN",
    "Welsh": "cy-GB",
    "Xhosa": "xh-ZA",
    "Yiddish": "yi-DE",
    "Yoruba": "yo-NG",
    "Zulu": "zu-ZA"}
